# Use the official Node.js image as a base
FROM node:14

# Set the working directory inside the container
WORKDIR .

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 5001
EXPOSE 5001

# Command to run the application
CMD ["node", "server.js"]